#!/usr/bin/env python3
r"""
Generate the hanzi -> pinyin table embedded in web/index.html.

Build-time tool only — the app itself stays dependency-free. This script pulls
Unicode's official Unihan database (cached in the temp dir, ~8.5 MB, downloaded
once with urllib from the stdlib) and rewrites the region between the
`PINYIN-TABLE:BEGIN` / `PINYIN-TABLE:END` markers in web/index.html.

Character set
    kTGHZ2013 (《通用规范汉字表》2013, 7.8k chars — crucially its level-3 block
    contains the place-name-only characters: 汕 郴 亳 婺 邯 郸 潍 歙 …)
    ∪ every Chinese character already present in data/*.json names, so nothing
    already in the app can ever fail to romanise.

Reading
    kMandarin (Unihan's preferred reading) first, kTGHZ2013's first reading as
    fallback. Tones stripped; ü written as u (石家庄 -> Shijiazhuang,
    吕梁 -> Luliang), matching how ASCII place names are usually written.
    Per-character pinyin cannot know context, so polyphonic place names
    (厦门, 六安, 哈尔滨 …) are handled by CITY_DICT in the frontend, which is
    consulted before this table.

Emitted JS
    const PY_SYL={a:"阿啊…",ai:"哀挨…",…}      // syllable -> chars, ~26 KB
    reversed into a char->syllable map at page load (see pinyinName()).

Usage
    python gen_pinyin_table.py           # rewrite web/index.html in place
    python gen_pinyin_table.py --check   # report only, touch nothing
"""
import argparse
import glob
import io
import json
import os
import re
import sys
import tempfile
import unicodedata
import urllib.request
import zipfile

ROOT = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(ROOT, "web", "index.html")
DATA = os.path.join(ROOT, "data")
URL = "https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip"
CACHE = os.path.join(tempfile.gettempdir(), "Unihan.zip")
BEGIN = "/* PINYIN-TABLE:BEGIN — generated by gen_pinyin_table.py, do not hand-edit */"
END = "/* PINYIN-TABLE:END */"

TONES = str.maketrans("āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜüêĕěê", "aaaaeeeeiiiioooouuuuuuuuueeee")

# Polyphonic characters where Unihan's preferred reading is not the one Chinese
# place names use. Verified against the official English station names in
# data/*.json (see the mismatch list this table was derived from):
#   长福路 Changfulu, 红土地 Hongtudi, 石佛 Shifo, 广都 Guangdu, 重光 Chongguang,
#   小什字 Xiaoshizi, 曾家岩 Zengjiayan, 茄子溪 Qiezixi, 龙爪堰 Longzhuayan, 厦门 Xiamen
# 长 and 厦 are the only two whose Traditional form is a SEPARATE character, and
# 台北/香港 brought both into the corpus (the other eight are unified). Unihan
# reads them zhang / sha, which is wrong for every occurrence in data/*.json:
#   長沙灣 Cheung Sha Wan, 長庚醫院 Chang Gung, 長壽山 Changshoushan, 機場第一航廈
OVERRIDE = {
    "长": "chang", "地": "di", "佛": "fo", "都": "du", "重": "chong",
    "什": "shi", "曾": "zeng", "茄": "qie", "爪": "zhua", "厦": "xia",
    "長": "chang", "廈": "xia",
}


def strip_tone(reading):
    r = unicodedata.normalize("NFC", reading).lower().translate(TONES)
    return re.sub(r"[^a-z]", "", r)


def fetch_unihan():
    if not os.path.exists(CACHE):
        print(f"downloading {URL}\n  -> {CACHE}")
        urllib.request.urlretrieve(URL, CACHE)
    print(f"Unihan: {CACHE} ({os.path.getsize(CACHE)} bytes)")
    return CACHE


def read_unihan(path):
    """-> (kMandarin readings, kTGHZ2013 readings) for U+4E00..U+9FFF"""
    mandarin, tghz = {}, {}
    with zipfile.ZipFile(path) as z:
        with z.open("Unihan_Readings.txt") as fh:
            for line in io.TextIOWrapper(fh, encoding="utf-8"):
                if not line.startswith("U+"):
                    continue
                cp, field, val = line.rstrip("\n").split("\t")
                n = int(cp[2:], 16)
                if not 0x4E00 <= n <= 0x9FFF:
                    continue
                if field == "kMandarin":
                    mandarin[chr(n)] = strip_tone(val.split()[0])
                elif field == "kTGHZ2013":
                    tghz[chr(n)] = strip_tone(val.split()[0].split(":")[-1])
    return mandarin, tghz


def app_corpus():
    """Every Chinese char used in the shipped city/station/line names."""
    chars = set()
    for path in glob.glob(os.path.join(DATA, "*.json")):
        doc = json.load(open(path, encoding="utf-8"))
        chars.update(doc["city"]["name_cn"])
        for s in doc["stations"]:
            chars.update(s["name_cn"])
        for l in doc["lines"]:
            chars.update(l["name"])
    html = open(HTML, encoding="utf-8").read()
    block = re.search(r"const CITY_DICT=\[(.*?)\n\];", html, re.S)
    if block:
        chars.update(block.group(1))
    return {c for c in chars if 0x4E00 <= ord(c) <= 0x9FFF}


def build_js(mandarin, tghz, corpus):
    selected = set(tghz) | corpus
    by_syllable, missing = {}, []
    for ch in sorted(selected):
        reading = OVERRIDE.get(ch) or mandarin.get(ch) or tghz.get(ch)
        if not reading or not re.fullmatch(r"[a-z]+", reading):
            missing.append(ch)
            continue
        by_syllable.setdefault(reading, []).append(ch)
    body = ",".join(f'{syl}:"{"".join(chars)}"'
                    for syl, chars in sorted(by_syllable.items()))
    js = f"const PY_SYL={{{body}}};"
    return js, selected, by_syllable, missing


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--check", action="store_true", help="report only, do not write")
    args = ap.parse_args()

    mandarin, tghz = read_unihan(fetch_unihan())
    corpus = app_corpus()
    js, selected, by_syllable, missing = build_js(mandarin, tghz, corpus)

    print(f"  kMandarin readings : {len(mandarin)}")
    print(f"  kTGHZ2013 charset  : {len(tghz)}")
    print(f"  app corpus         : {len(corpus)} (extra beyond kTGHZ2013: "
          f"{len(corpus - set(tghz))})")
    print(f"  table              : {len(selected) - len(missing)} chars, "
          f"{len(by_syllable)} syllables, {len(js.encode('utf-8'))/1024:.1f} KB")
    if missing:
        print(f"  ! no usable reading for {len(missing)}: {''.join(missing[:40])}")

    html = open(HTML, encoding="utf-8").read()
    if BEGIN not in html or END not in html:
        sys.exit(f"markers not found in {HTML} — add them first")
    head, rest = html.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n{js}\n{END}{tail}"

    if args.check:
        cur = html.split(BEGIN, 1)[1].split(END, 1)[0].strip()
        print("  in-file table is " + ("up to date" if cur == js else "STALE"))
        return
    with open(HTML, "w", encoding="utf-8", newline="") as f:   # UTF-8, no BOM
        f.write(new)
    print(f"wrote {HTML} ({os.path.getsize(HTML)} bytes)")


if __name__ == "__main__":
    main()
