-- =====================================================================
-- Metro Transfer — Postgres schema (deployment). SQLite twin: schema.sql
--
-- Kept as a separate file rather than generated, because the differences are
-- few and mechanical. They are ONLY these:
--
--   PRAGMA foreign_keys = ON            -> dropped (Postgres always enforces)
--   INTEGER PRIMARY KEY AUTOINCREMENT   -> bigint GENERATED BY DEFAULT AS IDENTITY
--   TEXT DEFAULT (datetime('now'))      -> text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
--   INTEGER (0/1 flags, counters)       -> smallint / integer
--   FKs onto answer                     -> + ON DELETE CASCADE
--
-- Deliberately NOT changed:
--   * timestamps stay `text` in the same 'YYYY-MM-DD HH24:MI:SS' shape. A real
--     timestamptz would break updated_at[:10] and comment created_at[:10], and —
--     worse — _days_since() swallows its exception, so every answer would silently
--     score as 0 days old and the whole ranking would flatten with no error.
--   * `alias` stays `text` holding a JSON string. As jsonb, json.loads() would get
--     a parsed list and the search LIKE would have no operator.
--   * is_anon / is_deleted stay 0/1 integers. As real booleans, four SQL
--     comparisons and two write paths would all need changing for no benefit.
--   * table `line` keeps its name. Verified against Postgres 18: a table named
--     `line` coexists fine with the built-in geometric type of the same name.
--
-- Drift between this file and schema.sql is checked by comparing the two column
-- sets after creating both (see the Phase B verification).
-- =====================================================================

CREATE TABLE IF NOT EXISTS country (
    id          text PRIMARY KEY,
    name_cn     text NOT NULL,
    name_en     text NOT NULL
);

CREATE TABLE IF NOT EXISTS city (
    id          text PRIMARY KEY,
    country_id  text REFERENCES country(id),
    name_cn     text NOT NULL,
    name_en     text NOT NULL,
    alias       text DEFAULT '',
    timezone    text DEFAULT 'UTC',
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    search_fold text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS metro_system (
    id          text PRIMARY KEY,
    city_id     text NOT NULL REFERENCES city(id),
    name_cn     text NOT NULL,
    name_en     text NOT NULL
);

CREATE TABLE IF NOT EXISTS line (
    id          text PRIMARY KEY,
    city_id     text NOT NULL REFERENCES city(id),
    system_id   text REFERENCES metro_system(id),
    name        text NOT NULL,
    name_en     text DEFAULT '',
    color       text DEFAULT '#4b5563',
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_line_city ON line(city_id);

CREATE TABLE IF NOT EXISTS direction (
    id          text PRIMARY KEY,
    line_id     text NOT NULL REFERENCES line(id),
    name        text NOT NULL,
    ordinal     integer DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_direction_line ON direction(line_id);

CREATE TABLE IF NOT EXISTS station (
    id          text PRIMARY KEY,
    city_id     text NOT NULL REFERENCES city(id),
    name_cn     text NOT NULL,
    name_en     text DEFAULT '',
    alias       text DEFAULT '',
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    search_fold text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_station_city ON station(city_id);

CREATE TABLE IF NOT EXISTS station_line (
    station_id  text NOT NULL REFERENCES station(id),
    line_id     text NOT NULL REFERENCES line(id),
    PRIMARY KEY (station_id, line_id)
);

CREATE TABLE IF NOT EXISTS transfer (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id     text NOT NULL REFERENCES station(id),
    from_line_id   text NOT NULL REFERENCES line(id),
    from_dir_id    text NOT NULL REFERENCES direction(id),
    to_line_id     text NOT NULL REFERENCES line(id),
    to_dir_id      text NOT NULL REFERENCES direction(id),
    UNIQUE (station_id, from_line_id, from_dir_id, to_line_id, to_dir_id)
);

CREATE TABLE IF NOT EXISTS app_user (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       text UNIQUE NOT NULL,
    nickname    text NOT NULL,
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS answer (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id   bigint NOT NULL REFERENCES transfer(id),
    user_id       bigint NOT NULL REFERENCES app_user(id),
    position_type text NOT NULL,
    car_number    integer,
    custom_text   text DEFAULT '',
    description   text DEFAULT '',
    is_anon       smallint DEFAULT 1,
    version       integer DEFAULT 1,
    is_deleted    smallint DEFAULT 0,
    created_at    text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at    text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (transfer_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_answer_transfer ON answer(transfer_id);

-- ON DELETE CASCADE on the three children of `answer`: SQLite let a parent delete
-- through when the pragma was off, Postgres never will. The importer no longer
-- deletes answers, but leaving these as NO ACTION would turn any future cleanup
-- into an FK error.
CREATE TABLE IF NOT EXISTS answer_version (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id     bigint NOT NULL REFERENCES answer(id) ON DELETE CASCADE,
    version       integer NOT NULL,
    position_type text NOT NULL,
    car_number    integer,
    custom_text   text DEFAULT '',
    description   text DEFAULT '',
    created_at    text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_version_answer ON answer_version(answer_id);

CREATE TABLE IF NOT EXISTS vote (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id   bigint NOT NULL REFERENCES answer(id) ON DELETE CASCADE,
    user_id     bigint NOT NULL REFERENCES app_user(id),
    type        text NOT NULL CHECK (type IN ('LIKE','DISLIKE')),
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (answer_id, user_id)
);

CREATE TABLE IF NOT EXISTS comment (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id   bigint NOT NULL REFERENCES answer(id) ON DELETE CASCADE,
    user_id     bigint NOT NULL REFERENCES app_user(id),
    content     text NOT NULL,
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_comment_answer ON comment(answer_id);

CREATE TABLE IF NOT EXISTS write_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device      text NOT NULL,
    kind        text NOT NULL,
    day         text NOT NULL,
    created_at  text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_write_log_quota ON write_log(device, day, kind);
